// src/popup/App.jsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { marked } from "marked";
import DOMPurify from "dompurify";

marked.setOptions({ breaks: true, gfm: true });
function renderMarkdown(text) {
  const html = marked.parse(text || "", { async: false });
  return DOMPurify.sanitize(html);
}

const AUTO_LOOP_DELAY_MS = 1200;
const AUTO_LOOP_MAX_ITERATIONS = 50;

const queryParams = new URLSearchParams(window.location.search);
const standaloneTargetTabId = Number(queryParams.get("targetTabId"));
const isStandaloneWindow = queryParams.get("standalone") === "1";

const iconUrl = chrome.runtime.getURL("icons/icon-48.png");

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function printForwardedEvents(messageType, response) {
  if (!response || !Array.isArray(response.events) || response.events.length === 0) return;
  const label = `[QSA forwarded] ${messageType} (${response.events.length})`;
  console.groupCollapsed(label);
  for (const event of response.events) {
    const logger = event.level === "warn" ? console.warn : console.log;
    logger(event.source || "[QSA]", event.message, event.details ?? "");
  }
  console.groupEnd();
}

function sendTabMessageOnce(tabId, message) {
  return new Promise((resolve, reject) => {
    chrome.tabs.sendMessage(tabId, message, (response) => {
      const error = chrome.runtime.lastError;
      if (error) {
        const err = new Error(error.message || "no-receiver");
        err.isNoReceiver = /Receiving end does not exist|message port closed|Could not establish connection/i.test(error.message || "");
        reject(err);
        return;
      }
      printForwardedEvents(message?.type, response);
      if (!response?.ok) {
        const err = new Error(response?.error || "Failed");
        err.diagnostics = response?.diagnostics || null;
        reject(err);
        return;
      }
      resolve(response.result);
    });
  });
}

function sendRuntimeMessage(message) {
  return new Promise((resolve, reject) => {
    chrome.runtime.sendMessage(message, (response) => {
      const error = chrome.runtime.lastError;
      if (error) { reject(new Error(error.message)); return; }
      printForwardedEvents(message?.type, response);
      if (!response?.ok) { reject(new Error(response?.error || "Request failed.")); return; }
      resolve(response.result);
    });
  });
}

async function getTargetTab() {
  if (Number.isInteger(standaloneTargetTabId) && standaloneTargetTabId > 0) {
    return chrome.tabs.get(standaloneTargetTabId);
  }
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab || null;
}

function captureTabScreenshot(tab, t) {
  return new Promise((resolve, reject) => {
    if (!tab?.windowId) { reject(new Error(t("errors.noScreenshotWindow"))); return; }
    chrome.tabs.captureVisibleTab(tab.windowId, { format: "jpeg", quality: 80 }, (dataUrl) => {
      const error = chrome.runtime.lastError;
      if (error) { reject(new Error(t("errors.screenshotFailed", { message: error.message }))); return; }
      resolve(dataUrl || "");
    });
  });
}

export default function App() {
  const { t } = useTranslation();

  const [status, setStatus] = useState(() => t("status.ready"));
  const [errorText, setErrorText] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [answerMode, setAnswerMode] = useState(false);
  const [autoMode, setAutoMode] = useState(false);
  const [detected, setDetected] = useState(null);
  const [messages, setMessages] = useState([]);
  const [draft, setDraft] = useState("");

  const messagesRef = useRef(null);
  const answerModeRef = useRef(answerMode);
  const autoModeRef = useRef(autoMode);
  useEffect(() => { answerModeRef.current = answerMode; }, [answerMode]);
  useEffect(() => { autoModeRef.current = autoMode; }, [autoMode]);

  // Suggestions come from locale as an array; cast to array safely
  const suggestions = useMemo(() => {
    const v = t("chat.suggestions", { returnObjects: true });
    return Array.isArray(v) ? v : [];
  }, [t]);

  useEffect(() => {
    document.body.classList.toggle("standalone", isStandaloneWindow);
    refreshSettingsStatus();
  }, []);

  useEffect(() => {
    if (!answerMode && autoMode) setAutoMode(false);
  }, [answerMode, autoMode]);

  useEffect(() => {
    const el = messagesRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [messages, isLoading]);

  const placeholderText = useMemo(() => {
    if (autoMode) return t("chat.placeholder.auto");
    if (answerMode) return t("chat.placeholder.answer");
    return t("chat.placeholder.chat");
  }, [answerMode, autoMode, t]);

  const detectedText = useMemo(() => {
    if (!detected) return "";
    const subject = detected.subject || detected.pageTitle || t("detected.pageContext");
    const count = detected.optionCount != null ? ` · ${t("detected.options", { count: detected.optionCount })}` : "";
    const screenshot = detected.hasScreenshot ? ` · ${t("detected.screenshot")}` : "";
    return `${subject}${count}${screenshot}`;
  }, [detected, t]);

  async function refreshSettingsStatus() {
    try {
      const settings = await sendRuntimeMessage({ type: "QSA_GET_SETTINGS" });
      if (!settings.backendUrl) setStatus(t("status.addBackend"));
      else if (!settings.hasSharedSecret) setStatus(t("status.noSecret"));
      else setStatus(t("status.ready"));
    } catch {
      setStatus(t("status.checkSettings"));
    }
  }

  const openOptions = useCallback(() => chrome.runtime.openOptionsPage(), []);

  const resetChat = useCallback(() => {
    setMessages([]);
    setDetected(null);
    setErrorText("");
    setStatus(t("status.ready"));
  }, [t]);

  const toggleAnswerMode = useCallback(() => setAnswerMode((v) => !v), []);
  const toggleAutoMode = useCallback(() => {
    setAutoMode((v) => {
      if (!answerModeRef.current) return false;
      return !v;
    });
  }, []);

  function modeLabel(mode, auto) {
    if (mode === "answer" && auto) return t("chat.modeLabel.auto");
    if (mode === "answer") return t("chat.modeLabel.answer");
    return t("chat.modeLabel.chat");
  }

  const sendTabMessage = useCallback(async (tabId, message, { retries = 6, retryDelayMs = 500 } = {}) => {
    for (let attempt = 0; attempt <= retries; attempt += 1) {
      try {
        return await sendTabMessageOnce(tabId, message);
      } catch (error) {
        if (!error?.isNoReceiver) throw error;
        if (attempt < retries) {
          console.log(`[QSA] tab not ready, retry ${attempt + 1}/${retries} in ${retryDelayMs}ms`);
          await delay(retryDelayMs);
        }
      }
    }
    throw new Error(t("errors.reloadPage"));
  }, [t]);

  const applyDemoAnswer = useCallback(async (tabId, answer) => {
    try {
      const applyResult = await sendTabMessage(tabId, {
        type: "QSA_APPLY_DEMO_ANSWER",
        payload: { answer }
      });
      setStatus(applyResult.advanced ? t("status.answerSelectedAdvanced") : t("status.answerSelected"));
      return Boolean(applyResult.advanced);
    } catch (error) {
      const msg = error instanceof Error ? error.message : t("errors.autoSelectFailed");
      setErrorText(msg);
      return false;
    }
  }, [sendTabMessage, t]);

  const runIteration = useCallback(async ({ initialUserText, iteration }) => {
    setErrorText("");
    const mode = answerModeRef.current ? "answer" : "chat";
    const userText = initialUserText || (mode === "answer"
      ? (iteration === 0 ? t("chat.userPrompt.firstAnswer") : t("chat.userPrompt.nextAnswer"))
      : "");

    if (!userText && mode !== "answer") {
      setErrorText(t("errors.needMessageOrAnswer"));
      return;
    }

    if (userText) {
      setMessages((prev) => [...prev, { role: "user", text: userText, modeLabel: modeLabel(mode, autoModeRef.current) }]);
    }

    setIsLoading(true);
    setStatus(iteration === 0
      ? t("status.reading")
      : t("status.movingNext", { n: iteration + 1 }));

    let assistantText = "";
    let advanced = false;

    try {
      const targetTab = await getTargetTab();
      if (!targetTab?.id) throw new Error(t("errors.noTab"));

      const [extracted, screenshotDataUrl] = await Promise.all([
        sendTabMessage(targetTab.id, { type: "QSA_EXTRACT_QUESTION" }).catch(() => null),
        captureTabScreenshot(targetTab, t)
      ]);

      setStatus(mode === "answer" ? t("status.requestingAnswer") : t("status.requestingHint"));

      // history excludes the just-added user message; backend gets it via userText
      let history = [];
      setMessages((prev) => {
        history = prev.slice(0, -1)
          .filter((m) => m.role === "user" || m.role === "assistant")
          .map((m) => ({ role: m.role, text: m.text }));
        return prev;
      });

      const response = await sendRuntimeMessage({
        type: "QSA_GET_HINT",
        payload: {
          ...(extracted || {}),
          mode,
          screenshotDataUrl,
          history,
          userText
        }
      });

      setDetected(response.detected);
      assistantText = response.hint;
      setMessages((prev) => [...prev, { role: "assistant", text: assistantText, modeLabel: modeLabel(mode, autoModeRef.current) }]);

      if (mode === "answer" && autoModeRef.current) {
        advanced = await applyDemoAnswer(targetTab.id, assistantText);
      } else {
        setStatus(mode === "answer" ? t("status.answerReady") : t("status.done"));
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : t("errors.requestFailed");
      setErrorText(msg);
      setStatus(t("status.error"));
      setIsLoading(false);
      return;
    }

    setIsLoading(false);

    if (
      advanced &&
      answerModeRef.current &&
      autoModeRef.current &&
      iteration + 1 < AUTO_LOOP_MAX_ITERATIONS
    ) {
      await delay(AUTO_LOOP_DELAY_MS);
      if (!autoModeRef.current) {
        setStatus(t("status.autoStopped"));
        return;
      }
      await runIteration({ initialUserText: "", iteration: iteration + 1 });
    } else if (advanced) {
      setStatus(t("status.autoFinished"));
    }
  }, [applyDemoAnswer, sendTabMessage, t]);

  const onSubmit = useCallback(async (e) => {
    e?.preventDefault();
    if (isLoading) return;
    const text = draft.trim();
    setDraft("");
    await runIteration({ initialUserText: text, iteration: 0 });
  }, [draft, isLoading, runIteration]);

  const useSuggestion = useCallback(async (text) => {
    if (isLoading) return;
    setDraft("");
    await runIteration({ initialUserText: text, iteration: 0 });
  }, [isLoading, runIteration]);

  const onKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey && !e.metaKey && !e.ctrlKey) {
      e.preventDefault();
      onSubmit();
    }
  };

  return (
    <main className="grid grid-rows-[auto_auto_1fr_auto] flex-1 min-h-0">
      <header className="flex items-center gap-2.5 px-3.5 py-3 border-b border-line bg-surface">
        <div className="flex items-center gap-2.5 flex-1 min-w-0">
          <img src={iconUrl} alt="" className="w-7 h-7 rounded-md bg-accent-soft p-[3px] object-contain" />
          <div className="min-w-0">
            <h1 className="m-0 text-[13px] font-semibold tracking-tight">{t("app.name")}</h1>
            <p className="mt-px mb-0 text-[11px] text-ink-3 truncate">{status}</p>
          </div>
        </div>
        <button
          type="button"
          title={t("app.settings")}
          aria-label={t("app.settings")}
          onClick={openOptions}
          className="w-[30px] h-[30px] rounded-md text-ink-2 text-[15px] hover:bg-surface-soft hover:text-ink-1 transition-colors"
        >⚙</button>
      </header>

      {detectedText && (
        <section className="flex items-center gap-2 px-3.5 py-1.5 border-b border-line bg-surface-soft text-[11px] text-ink-2">
          <span className="w-1.5 h-1.5 rounded-full bg-accent shrink-0" />
          <span className="truncate">{detectedText}</span>
        </section>
      )}

      <section
        ref={messagesRef}
        className="flex flex-col overflow-y-auto min-h-0 px-3.5 py-4 qsa-scroll"
        aria-live="polite"
      >
        <div className="flex flex-col gap-3.5 mt-auto">
          {messages.map((msg, i) => (
            <article
              key={i}
              className={msg.role === "user"
                ? "flex flex-col gap-1 self-end max-w-[85%] px-3.5 py-2.5 rounded-2xl rounded-br bg-accent-soft text-ink-1 text-sm leading-relaxed break-words"
                : "flex flex-col gap-1 self-stretch text-ink-1 text-sm leading-relaxed break-words"
              }
            >
              {msg.role === "assistant" && (
                <div className="flex gap-1.5 items-center text-[11px] font-semibold text-ink-3">
                  {t("chat.assistant")}
                  {msg.modeLabel && (
                    <span className="px-1.5 py-px text-[10px] rounded font-medium bg-secondary-soft text-secondary">
                      {msg.modeLabel}
                    </span>
                  )}
                </div>
              )}
              {msg.role === "assistant" ? (
                <div className="markdown" dangerouslySetInnerHTML={{ __html: renderMarkdown(msg.text) }} />
              ) : (
                <div className="whitespace-pre-wrap">{msg.text}</div>
              )}
            </article>
          ))}

          {isLoading && (
            <article className="flex flex-col gap-1 self-stretch">
              <div className="flex gap-1.5 items-center text-[11px] font-semibold text-ink-3">{t("chat.assistant")}</div>
              <div className="flex gap-1 py-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-ink-3 qsa-bounce" />
                <span className="w-1.5 h-1.5 rounded-full bg-accent qsa-bounce" style={{ animationDelay: "0.15s" }} />
                <span className="w-1.5 h-1.5 rounded-full bg-secondary qsa-bounce" style={{ animationDelay: "0.3s" }} />
              </div>
            </article>
          )}
        </div>
      </section>

      <section className="flex flex-col gap-2 px-3.5 pt-2.5 pb-3.5 border-t border-line bg-surface">
        {messages.length === 0 && suggestions.length > 0 && (
          <div className="flex flex-col gap-1.5 mb-0.5">
            {suggestions.map((s, i) => (
              <button
                key={i}
                type="button"
                onClick={() => useSuggestion(s)}
                className="text-left px-3 py-2 border border-line rounded-[10px] bg-surface text-ink-1 text-[13px] leading-snug hover:border-accent hover:bg-accent-soft hover:text-accent transition-colors"
              >{s}</button>
            ))}
          </div>
        )}

        <div className="flex gap-1.5 flex-wrap items-center" role="group" aria-label="Modes">
          <button
            type="button"
            onClick={toggleAnswerMode}
            title={answerMode ? t("toggles.answerOnlyTooltip.on") : t("toggles.answerOnlyTooltip.off")}
            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[12px] font-medium border transition-colors ${
              answerMode
                ? "text-accent bg-accent-soft border-accent"
                : "text-ink-2 bg-surface border-line hover:text-ink-1 hover:border-line-strong"
            }`}
          >
            <span className={`w-1.5 h-1.5 rounded-full ${answerMode ? "bg-accent" : "bg-ink-3"}`} />
            {t("toggles.answerOnly")}
          </button>
          <button
            type="button"
            onClick={toggleAutoMode}
            disabled={!answerMode}
            title={autoMode ? t("toggles.autoModeTooltip.on") : t("toggles.autoModeTooltip.off")}
            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[12px] font-medium border transition-colors disabled:opacity-50 disabled:cursor-not-allowed ${
              autoMode
                ? "text-secondary bg-secondary-soft border-secondary"
                : "text-ink-2 bg-surface border-line hover:text-ink-1 hover:border-line-strong"
            }`}
          >
            <span className={`w-1.5 h-1.5 rounded-full ${autoMode ? "bg-secondary" : "bg-ink-3"}`} />
            {t("toggles.autoMode")}
          </button>
          {messages.length > 0 && (
            <button
              type="button"
              onClick={resetChat}
              title={t("chat.clear")}
              className="ml-auto px-2.5 py-1 rounded-full text-[12px] text-ink-3 hover:text-ink-1 hover:bg-surface-soft transition-colors"
            >{t("chat.clear")}</button>
          )}
        </div>

        <form onSubmit={onSubmit} className="flex items-end gap-2 px-2.5 py-2 border border-line rounded-xl bg-surface focus-within:border-accent transition-colors">
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={onKeyDown}
            placeholder={placeholderText}
            rows={2}
            className="flex-1 resize-none max-h-[140px] border-0 bg-transparent text-ink-1 text-sm leading-snug outline-none placeholder:text-ink-3"
          />
          <button
            type="submit"
            disabled={isLoading}
            aria-label={t("chat.send")}
            className="w-8 h-8 shrink-0 rounded-lg bg-accent text-white text-base font-semibold hover:bg-accent-hover disabled:bg-line-strong disabled:cursor-not-allowed transition-colors"
          >{isLoading ? "…" : "↑"}</button>
        </form>

        {errorText && (
          <p className="m-0 px-2.5 py-1.5 rounded-lg bg-red-50 border border-red-200 text-red-600 text-[12px]">
            {errorText}
          </p>
        )}
      </section>
    </main>
  );
}

// src/popup/App.vue
<template>
  <main class="popup">
    <header class="header">
      <div class="brand">
        <img class="app-icon" :src="iconUrl" alt="">
        <div class="brand-text">
          <h1>Quiz Study Assistant</h1>
          <p class="status">{{ status }}</p>
        </div>
      </div>
      <button class="icon-button" type="button" title="Настройки" aria-label="Настройки" @click="openOptions">⚙</button>
    </header>

    <section v-if="detectedText" class="detected" aria-live="polite">
      <span class="detected-dot"></span>
      <span>{{ detectedText }}</span>
    </section>

    <section ref="messagesEl" class="messages" aria-live="polite">
      <div class="messages-inner">
        <article
          v-for="(msg, index) in messages"
          :key="index"
          class="msg"
          :class="msg.role"
        >
          <div class="msg-role">{{ msg.role === 'user' ? 'Ты' : 'Ассистент' }}<span v-if="msg.modeLabel" class="msg-tag">{{ msg.modeLabel }}</span></div>
          <div v-if="msg.role === 'assistant'" class="msg-body markdown" v-html="renderMarkdown(msg.text)"></div>
          <div v-else class="msg-body">{{ msg.text }}</div>
        </article>
        <article v-if="isLoading" class="msg assistant pending">
          <div class="msg-role">Ассистент</div>
          <div class="msg-body"><span class="dot"></span><span class="dot"></span><span class="dot"></span></div>
        </article>
      </div>
    </section>

    <section class="composer">
      <div v-if="messages.length === 0" class="suggestions">
        <button
          v-for="(s, i) in suggestions"
          :key="i"
          type="button"
          class="suggestion"
          @click="useSuggestion(s)"
        >{{ s }}</button>
      </div>

      <div class="composer-toggles" role="group" aria-label="Режимы">
        <button
          type="button"
          class="toggle"
          :class="{ active: answerMode }"
          @click="toggleAnswerMode"
          :title="answerMode ? 'Выключить «Ответ сразу»' : 'Возвращать только ответ'"
        >
          <span class="toggle-dot"></span>
          Ответ сразу
        </button>
        <button
          type="button"
          class="toggle toggle-secondary"
          :class="{ active: autoMode, disabled: !answerMode }"
          :disabled="!answerMode"
          @click="toggleAutoMode"
          :title="autoMode ? 'Выключить авто-режим' : 'Выбирать ответ и переходить дальше'"
        >
          <span class="toggle-dot"></span>
          Авто-режим
        </button>
        <button
          v-if="messages.length > 0"
          type="button"
          class="clear"
          @click="resetChat"
          title="Очистить диалог"
        >Очистить</button>
      </div>
      <form class="composer-form" @submit.prevent="onSubmit">
        <textarea
          ref="inputEl"
          v-model="draft"
          class="composer-input"
          :placeholder="placeholderText"
          rows="2"
          @keydown.enter.exact.prevent="onSubmit"
        ></textarea>
        <button class="send" type="submit" :disabled="isLoading || (!draft.trim() && !answerMode && messages.length === 0 && !autoMode)">
          <span v-if="isLoading">…</span>
          <span v-else>↑</span>
        </button>
      </form>
      <p v-if="errorText" class="error-banner">{{ errorText }}</p>
    </section>
  </main>
</template>

<script setup>
import { computed, nextTick, onMounted, ref, watch } from "vue";
import { marked } from "marked";
import DOMPurify from "dompurify";

marked.setOptions({ breaks: true, gfm: true });
function renderMarkdown(text) {
  const html = marked.parse(text || "", { async: false });
  return DOMPurify.sanitize(html);
}

const AUTO_LOOP_DELAY_MS = 1200;
const AUTO_LOOP_MAX_ITERATIONS = 50;

const status = ref("Готово");
const errorText = ref("");
const isLoading = ref(false);
const answerMode = ref(false);
const autoMode = ref(false);
const detected = ref(null);
const messages = ref([]);
const draft = ref("");
const iconUrl = chrome.runtime.getURL("icons/icon-48.png");

const suggestions = [
  "Разбери для меня текущий вопрос",
  "Объясни ключевое понятие простыми словами",
  "Какие варианты точно неправильные и почему?"
];

const messagesEl = ref(null);
const inputEl = ref(null);

const queryParams = new URLSearchParams(window.location.search);
const standaloneTargetTabId = Number(queryParams.get("targetTabId"));
const isStandaloneWindow = queryParams.get("standalone") === "1";

const placeholderText = computed(() => {
  if (autoMode.value) return "Авто-режим: жми ↑, я буду выбирать ответы и переходить дальше.";
  if (answerMode.value) return "Жми ↑, чтобы получить только ответ. Можешь добавить уточнение.";
  return "Спроси про вопрос, попроси разобрать вариант, дай уточнение...";
});

const detectedText = computed(() => {
  if (!detected.value) return "";
  const subject = detected.value.subject || detected.value.pageTitle || "Контекст страницы";
  const count = detected.value.optionCount != null ? ` · ${detected.value.optionCount} вариантов` : "";
  const screenshot = detected.value.hasScreenshot ? " · скриншот" : "";
  return `${subject}${count}${screenshot}`;
});

onMounted(() => {
  document.body.classList.toggle("standalone", isStandaloneWindow);
  refreshSettingsStatus();
});

watch(answerMode, (value) => {
  if (!value && autoMode.value) autoMode.value = false;
});

watch([messages, isLoading], () => {
  nextTick(scrollMessagesToBottom);
}, { deep: true });

function openOptions() {
  chrome.runtime.openOptionsPage();
}

function toggleAnswerMode() {
  answerMode.value = !answerMode.value;
}

function toggleAutoMode() {
  if (!answerMode.value) return;
  autoMode.value = !autoMode.value;
}

function resetChat() {
  messages.value = [];
  detected.value = null;
  errorText.value = "";
  status.value = "Готово";
}

function scrollMessagesToBottom() {
  const el = messagesEl.value;
  if (!el) return;
  el.scrollTop = el.scrollHeight;
}

async function onSubmit() {
  if (isLoading.value) return;
  const text = draft.value.trim();
  draft.value = "";
  await runIteration({ initialUserText: text, iteration: 0 });
}

async function useSuggestion(text) {
  if (isLoading.value) return;
  draft.value = "";
  await runIteration({ initialUserText: text, iteration: 0 });
}

function pickMode() {
  if (answerMode.value) return "answer";
  return "chat";
}

function modeLabel(mode, auto) {
  if (mode === "answer" && auto) return "Авто";
  if (mode === "answer") return "Ответ";
  if (mode === "chat") return "Чат";
  return "Подсказка";
}

async function runIteration({ initialUserText, iteration }) {
  errorText.value = "";
  const mode = pickMode();
  const userText = initialUserText || (mode === "answer"
    ? (iteration === 0 ? "Дай ответ на текущий вопрос" : "Дай ответ на этот вопрос")
    : "");

  if (userText) {
    messages.value.push({ role: "user", text: userText, modeLabel: modeLabel(mode, autoMode.value) });
  } else if (mode !== "answer") {
    // chat mode with empty input — nothing to send
    errorText.value = "Введи сообщение или включи «Ответ сразу».";
    return;
  }

  isLoading.value = true;
  status.value = iteration === 0
    ? "Читаю вопрос и делаю скриншот..."
    : `Перехожу к следующему вопросу #${iteration + 1}...`;

  let assistantText = "";
  let advanced = false;

  try {
    const targetTab = await getTargetTab();
    if (!targetTab?.id) throw new Error("Не удалось найти активную вкладку.");

    const [extracted, screenshotDataUrl] = await Promise.all([
      sendTabMessage(targetTab.id, { type: "QSA_EXTRACT_QUESTION" }).catch(() => null),
      captureTabScreenshot(targetTab)
    ]);

    status.value = mode === "answer"
      ? "Запрашиваю ответ..."
      : "Запрашиваю подсказку...";

    const history = messages.value
      .slice(0, -1) // exclude the just-added user message; backend will get it via userText
      .filter((m) => m.role === "user" || m.role === "assistant")
      .map((m) => ({ role: m.role, text: m.text }));

    const response = await sendRuntimeMessage({
      type: "QSA_GET_HINT",
      payload: {
        ...(extracted || {}),
        mode,
        screenshotDataUrl,
        history,
        userText
      }
    });

    detected.value = response.detected;
    assistantText = response.hint;
    messages.value.push({ role: "assistant", text: assistantText, modeLabel: modeLabel(mode, autoMode.value) });

    if (mode === "answer" && autoMode.value) {
      advanced = await applyDemoAnswer(targetTab.id, assistantText);
    } else {
      status.value = mode === "answer" ? "Ответ готов" : "Готово";
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : "Не удалось выполнить запрос.";
    errorText.value = message;
    status.value = "Ошибка";
    isLoading.value = false;
    return;
  }

  isLoading.value = false;

  if (
    advanced &&
    answerMode.value &&
    autoMode.value &&
    iteration + 1 < AUTO_LOOP_MAX_ITERATIONS
  ) {
    await delay(AUTO_LOOP_DELAY_MS);
    if (!autoMode.value) {
      status.value = "Авто-режим остановлен.";
      return;
    }
    await runIteration({ initialUserText: "", iteration: iteration + 1 });
  } else if (advanced) {
    status.value = "Авто-режим завершён.";
  }
}

async function applyDemoAnswer(tabId, answer) {
  try {
    const applyResult = await sendTabMessage(tabId, {
      type: "QSA_APPLY_DEMO_ANSWER",
      payload: { answer }
    });
    status.value = applyResult.advanced ? "Ответ выбран · переход выполнен" : "Ответ выбран";
    return Boolean(applyResult.advanced);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Ответ готов, но автовыбор недоступен.";
    errorText.value = message;
    return false;
  }
}

async function refreshSettingsStatus() {
  try {
    const settings = await sendRuntimeMessage({ type: "QSA_GET_SETTINGS" });
    if (!settings.backendUrl) {
      status.value = "Добавь адрес backend в настройках";
    } else if (!settings.hasSharedSecret) {
      status.value = "Backend подключен без секрета";
    } else {
      status.value = "Готово";
    }
  } catch {
    status.value = "Проверь настройки расширения";
  }
}

function printForwardedEvents(messageType, response) {
  if (!response || !Array.isArray(response.events) || response.events.length === 0) return;
  const label = `[QSA forwarded] ${messageType} (${response.events.length})`;
  console.groupCollapsed(label);
  for (const event of response.events) {
    const logger = event.level === "warn" ? console.warn : console.log;
    logger(event.source || "[QSA]", event.message, event.details ?? "");
  }
  console.groupEnd();
}

function sendTabMessageOnce(tabId, message) {
  return new Promise((resolve, reject) => {
    chrome.tabs.sendMessage(tabId, message, (response) => {
      const error = chrome.runtime.lastError;
      if (error) {
        const err = new Error(error.message || "no-receiver");
        err.isNoReceiver = /Receiving end does not exist|message port closed|Could not establish connection/i.test(error.message || "");
        reject(err);
        return;
      }
      printForwardedEvents(message?.type, response);
      if (!response?.ok) {
        const err = new Error(response?.error || "Не удалось прочитать страницу.");
        err.diagnostics = response?.diagnostics || null;
        reject(err);
        return;
      }
      resolve(response.result);
    });
  });
}

async function sendTabMessage(tabId, message, { retries = 6, retryDelayMs = 500 } = {}) {
  for (let attempt = 0; attempt <= retries; attempt += 1) {
    try {
      return await sendTabMessageOnce(tabId, message);
    } catch (error) {
      if (!error?.isNoReceiver) throw error;
      if (attempt < retries) {
        console.log(`[QSA] tab not ready, retry ${attempt + 1}/${retries} in ${retryDelayMs}ms`);
        await delay(retryDelayMs);
      }
    }
  }
  throw new Error("Обнови страницу теста и попробуй снова.");
}

function sendRuntimeMessage(message) {
  return new Promise((resolve, reject) => {
    chrome.runtime.sendMessage(message, (response) => {
      const error = chrome.runtime.lastError;
      if (error) {
        reject(new Error(error.message));
        return;
      }
      printForwardedEvents(message?.type, response);
      if (!response?.ok) {
        reject(new Error(response?.error || "Не удалось выполнить запрос."));
        return;
      }
      resolve(response.result);
    });
  });
}

async function getTargetTab() {
  if (Number.isInteger(standaloneTargetTabId) && standaloneTargetTabId > 0) {
    return chrome.tabs.get(standaloneTargetTabId);
  }
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab || null;
}

function captureTabScreenshot(tab) {
  return new Promise((resolve, reject) => {
    if (!tab?.windowId) {
      reject(new Error("Не удалось определить окно вкладки для скриншота."));
      return;
    }
    chrome.tabs.captureVisibleTab(tab.windowId, { format: "jpeg", quality: 80 }, (dataUrl) => {
      const error = chrome.runtime.lastError;
      if (error) {
        reject(new Error(`Не удалось сделать скриншот: ${error.message}`));
        return;
      }
      resolve(dataUrl || "");
    });
  });
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
</script>
